// <auto-generated />
using System;
using ApiPaises.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiPaises.Migrations
{
    [DbContext(typeof(ApiPaisesContext))]
    partial class ApiPaisesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiPaises.Domain.Estados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("PaisesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("fotoEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("paisId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PaisesId");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("ApiPaises.Domain.Paises", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("urlFoto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("ApiPaises.Domain.Estados", b =>
                {
                    b.HasOne("ApiPaises.Domain.Paises", null)
                        .WithMany("Estados")
                        .HasForeignKey("PaisesId");
                });
#pragma warning restore 612, 618
        }
    }
}
